#!/usr/bin/env bash
# test/t94_destroy_unreachable_grep.sh
#
# T99 — Seam B partial: DESTROY unreachability cross-file grep test
#
# Two assertions:
#
#   A. ConfirmModal import isolation: grep for ConfirmModal imports across
#      flow-monitor/src/**/*.ts* must find matches only in:
#        - the component definition itself (ConfirmModal.tsx)
#        - its unit test (__tests__/ConfirmModal.test.tsx)
#      Any import from another file is a violation — it means a caller
#      has imported the DESTROY-path component before B3 authorises it.
#
#   B. DESTROY-command slug isolation: grep for the four destroy-related
#      command slugs (archive, update-prd, update-plan, update-tech,
#      update-tasks) across flow-monitor/src/**/*.ts* must find matches
#      only in src/generated/command_taxonomy.ts (the authoritative list).
#      Any other match means a caller is hard-coding slugs that should
#      be consumed only through classify() / allow_list_contains().
#
# Vacuous-pass behaviour:
#   - During W3 ConfirmModal does not exist yet (T104 in W4 authors it).
#     The grep will find zero matches → no violation → pass vacuously.
#     The real enforcement kicks in at W4 merge and beyond.
#   - src/generated/command_taxonomy.ts is a build artefact (gitignored,
#     regenerated by `cargo build`).  If it does not exist the grep will
#     find zero matches → no unexpected matches → pass vacuously.
#     If it exists any match outside that file is still a violation.
#
# Sandbox-HOME NOT required: this test only runs grep against the repo
# working tree and never invokes any CLI that expands or writes $HOME.
# (bash/sandbox-home-in-tests.md — explicitly exempt for read-only repo
# traversal scripts.)
#
# Bash 3.2 / BSD portable:
#   no readlink -f, realpath, jq, mapfile/readarray, [[ =~ ]], GNU-only
#   flags.  No `case` inside subshells (bash32-case-in-subshell.md).
set -euo pipefail

# ---------------------------------------------------------------------------
# Locate repo root relative to this script
# (developer/test-script-path-convention.md — never hardcode worktree path)
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd -P)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd -P)"

SRC_DIR="$REPO_ROOT/flow-monitor/src"

# ---------------------------------------------------------------------------
# Preflight — src directory must exist
# ---------------------------------------------------------------------------
if [ ! -d "$SRC_DIR" ]; then
  printf 'SKIP: %s not found — flow-monitor not present; re-run after app scaffold.\n' \
    "$SRC_DIR" >&2
  exit 0
fi

# ---------------------------------------------------------------------------
# Test harness helpers
# ---------------------------------------------------------------------------
PASS=0
FAIL=0

pass() { printf 'PASS: %s\n' "$1"; PASS=$((PASS + 1)); }
fail() { printf 'FAIL: %s\n' "$1" >&2; FAIL=$((FAIL + 1)); }

# ---------------------------------------------------------------------------
# A. ConfirmModal import isolation
#
# Pattern: any TypeScript file that imports from ConfirmModal.
# Allowed files (suffix matches — path ends with one of these):
#   .../ConfirmModal.tsx
#   .../__tests__/ConfirmModal.test.tsx
#
# If ConfirmModal does not exist at all the grep exits non-zero with no
# output; we treat that as a vacuous pass (W3 state — T104 not yet merged).
# ---------------------------------------------------------------------------
printf '=== A: ConfirmModal import isolation ===\n'

# Run grep; suppress the non-zero exit when there are no matches at all
# (grep -r returns 1 when nothing matches; || true prevents set -e abort).
CONFIRM_MATCHES="$(grep -rE 'from .+ConfirmModal|import.+ConfirmModal' \
  "$SRC_DIR" --include='*.ts' --include='*.tsx' 2>/dev/null || true)"

if [ -z "$CONFIRM_MATCHES" ]; then
  pass "A: no ConfirmModal imports found — vacuous pass (ConfirmModal not yet authored)"
else
  # Examine each matching line; fail if from a file other than the two
  # allowed paths.  We parse grep's "filename:content" output: the part
  # before the first colon is the file path.
  A_VIOLATIONS=0
  while IFS= read -r line; do
    # Extract the file path (everything before the first colon).
    # Use POSIX parameter expansion — no sed/awk subprocess per iteration.
    filepath="${line%%:*}"

    # Determine whether this file is in the allowed set.
    # Allowed: path ends with /ConfirmModal.tsx or /__tests__/ConfirmModal.test.tsx
    # Using suffix-strip test (POSIX, no [[ =~ ]]).
    _base="$(basename "$filepath")"
    _parent_base="$(basename "$(dirname "$filepath")")"

    allowed=0
    if [ "$_base" = "ConfirmModal.tsx" ] && [ "$_parent_base" != "__tests__" ]; then
      allowed=1
    fi
    if [ "$_base" = "ConfirmModal.test.tsx" ] && [ "$_parent_base" = "__tests__" ]; then
      allowed=1
    fi

    if [ "$allowed" -eq 0 ]; then
      printf 'FAIL A: unexpected ConfirmModal import in %s\n' "$filepath" >&2
      A_VIOLATIONS=$((A_VIOLATIONS + 1))
    fi
  done <<EOF
$CONFIRM_MATCHES
EOF

  if [ "$A_VIOLATIONS" -eq 0 ]; then
    pass "A: all ConfirmModal imports are confined to ConfirmModal.tsx and its test"
  else
    fail "A: $A_VIOLATIONS unexpected ConfirmModal import(s) found — see lines above"
  fi
fi

# ---------------------------------------------------------------------------
# B. DESTROY-command slug isolation
#
# Pattern: hard-coded command slugs (archive|update-prd|update-plan|
# update-tech|update-tasks) anywhere in TypeScript source.
# The only allowed file is src/generated/command_taxonomy.ts, which is the
# single authoritative source generated by build.rs (D3).
#
# Skip behaviour when taxonomy file is absent:
#   src/generated/command_taxonomy.ts is a gitignored build artefact
#   regenerated by `cargo build`.  The file does not exist until W2's
#   build.rs task has run.  We assert only when the file is present:
#   if it exists, any match outside it is a violation; if it is absent
#   the entire assertion is skipped vacuously.  This lets the test pass
#   during W3 (and W4/W5 if cargo build hasn't run) while still binding
#   at W6 merge-time when the full tree is built.
# ---------------------------------------------------------------------------
printf '\n=== B: DESTROY-command slug isolation ===\n'

TAXONOMY_FILE="$SRC_DIR/generated/command_taxonomy.ts"

if [ ! -f "$TAXONOMY_FILE" ]; then
  pass "B: src/generated/command_taxonomy.ts absent (cargo build not yet run) — vacuous pass"
else
  # Taxonomy exists — grep the full src tree and fail on any hit outside it.
  # Suppress exit 1 (no matches) with || true.
  SLUG_MATCHES="$(grep -rwE '(archive|update-prd|update-plan|update-tech|update-tasks)' \
    "$SRC_DIR" --include='*.ts' --include='*.tsx' 2>/dev/null || true)"

  if [ -z "$SLUG_MATCHES" ]; then
    pass "B: no command-slug matches found anywhere — taxonomy file exists but is empty or unmatched"
  else
    B_VIOLATIONS=0
    while IFS= read -r line; do
      filepath="${line%%:*}"

      if [ "$filepath" != "$TAXONOMY_FILE" ]; then
        printf 'FAIL B: command slug found outside taxonomy file in %s\n' "$filepath" >&2
        B_VIOLATIONS=$((B_VIOLATIONS + 1))
      fi
    done <<EOF
$SLUG_MATCHES
EOF

    if [ "$B_VIOLATIONS" -eq 0 ]; then
      pass "B: all command-slug matches are confined to src/generated/command_taxonomy.ts"
    else
      fail "B: $B_VIOLATIONS unexpected command-slug match(es) found — see lines above"
    fi
  fi
fi

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
printf '\n=== Results: %d passed, %d failed ===\n' "$PASS" "$FAIL"
[ "$FAIL" -eq 0 ]
