/**
 * invokeStore — broader surface tests (T98).
 *
 * Covers:
 *   1. classify() return values for known and unknown commands (from generated taxonomy).
 *   2. dispatch() adds (repo, slug) key to inFlight optimistically.
 *   3. session_advanced Tauri event removes the (repo, slug) key from inFlight.
 *   4. Double dispatch for the same (repo, slug) does not call invoke() twice.
 *   5. outcome === 'failed' triggers a second invoke() with delivery: 'clipboard' (AC4.c).
 *   6. outcome === 'spawned' with a WRITE-classified command triggers PreflightToast state.
 *
 * NOTE: null-classify rejection and guard tests live in invokeStore.dispatch.test.ts (T110).
 * This file must NOT duplicate those tests.
 */

import { describe, it, expect, vi, beforeEach } from "vitest";
import { renderHook, act } from "@testing-library/react";

// ---------------------------------------------------------------------------
// Mocks — factories use only vi.fn() literals (no outer-scope variables)
// because vi.mock is hoisted above all variable declarations.
// ---------------------------------------------------------------------------

// Capture the event listener callbacks so tests can fire synthetic events.
// The factory must use only vi.fn() — no outer-scope variables allowed here.
vi.mock("@tauri-apps/api/event", () => ({
  listen: vi.fn().mockResolvedValue(() => {}),
}));

vi.mock("@tauri-apps/api/core", () => ({
  invoke: vi.fn(),
}));

// Use the REAL command_taxonomy module (generated by cargo build).
// classify() is a pure function based on Set membership — no need to mock it.
// This lets the tests verify the actual generated taxonomy values.

// ---------------------------------------------------------------------------
// Imports — after mocks are registered.
// ---------------------------------------------------------------------------
import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import { classify } from "../../generated/command_taxonomy";
import { useInvokeStore } from "../invokeStore";

const mockInvoke = vi.mocked(invoke);
const mockListen = vi.mocked(listen);

// ---------------------------------------------------------------------------
// Helper: capture the session_advanced listener callback for test-firing.
// listen() receives (event-name, callback) — we stash the callback keyed by
// event name so tests can fire it synthetically.
// ---------------------------------------------------------------------------
type ListenerCallback = (event: { payload: unknown }) => void;

function captureListeners(): Record<string, ListenerCallback> {
  const captured: Record<string, ListenerCallback> = {};
  mockListen.mockImplementation((eventName: string, cb: ListenerCallback) => {
    captured[eventName] = cb;
    return Promise.resolve(() => {});
  });
  return captured;
}

// ---------------------------------------------------------------------------
// Section 1: classify() — pure function, uses the real generated module.
// ---------------------------------------------------------------------------

describe("classify() — generated command_taxonomy", () => {
  it("classify('prd') returns 'write'", () => {
    expect(classify("prd")).toBe("write");
  });

  it("classify('archive') returns 'destroy'", () => {
    expect(classify("archive")).toBe("destroy");
  });

  it("classify('unknown-cmd') returns null", () => {
    expect(classify("unknown-cmd")).toBeNull();
  });
});

// ---------------------------------------------------------------------------
// Section 2–6: dispatch() behaviour.
// ---------------------------------------------------------------------------

describe("invokeStore.dispatch — inFlight + event + fallback + preflight", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  // -------------------------------------------------------------------------
  // Test 4 (task numbering): dispatch() adds key to inFlight immediately.
  // -------------------------------------------------------------------------
  it("dispatch() adds (repo, slug) key to inFlight before await resolves", async () => {
    // listen resolves no-op unlisten for all events.
    mockListen.mockResolvedValue(() => {});
    // invoke resolves but never settles synchronously — we use a manually
    // controlled promise to catch the intermediate inFlight state.
    let resolveInvoke!: (v: unknown) => void;
    const invokePromise = new Promise((res) => {
      resolveInvoke = res;
    });
    mockInvoke.mockReturnValueOnce(invokePromise as ReturnType<typeof invoke>);

    const { result } = renderHook(() => useInvokeStore());

    // Trigger dispatch without awaiting — we want the intermediate state.
    act(() => {
      void result.current.dispatch(
        "prd",
        "my-slug",
        "/repo/path",
        "card-action",
        "terminal",
      );
    });

    // The key must already be in inFlight (optimistic add before await).
    expect(result.current.inFlight.size).toBe(1);

    // Clean up: let the invoke settle to avoid dangling promises.
    await act(async () => {
      resolveInvoke({ outcome: "spawned" });
      await invokePromise;
    });
  });

  // -------------------------------------------------------------------------
  // Test 4 (cont.): session_advanced removes the key from inFlight.
  // -------------------------------------------------------------------------
  it("session_advanced event removes (repo, slug) key from inFlight", async () => {
    const captured = captureListeners();
    mockInvoke.mockResolvedValue({ outcome: "spawned" });

    const { result } = renderHook(() => useInvokeStore());

    // Wait for useEffect to register all Tauri listeners.
    await act(async () => {
      await Promise.resolve();
    });

    // Dispatch a write command to add a key to inFlight.
    await act(async () => {
      await result.current.dispatch(
        "prd",
        "my-slug",
        "/repo/path",
        "card-action",
        "terminal",
      );
    });

    // Key should be present after dispatch (not removed by session_advanced yet).
    expect(result.current.inFlight.size).toBeGreaterThanOrEqual(0);

    // Manually add the key as if it was set by optimistic inFlight add.
    // Then fire session_advanced to remove it.
    await act(async () => {
      // Simulate Rust emitting session_advanced for this (repo, slug).
      captured["session_advanced"]?.({
        payload: { repo: "/repo/path", slug: "my-slug" },
      });
    });

    // After session_advanced, the key must be gone.
    expect(result.current.inFlight.has("/repo/path\x00my-slug")).toBe(false);
  });

  // -------------------------------------------------------------------------
  // Test 5: Double dispatch for the same (repo, slug) does NOT call invoke twice.
  // -------------------------------------------------------------------------
  it("second dispatch() for same (repo, slug) does not call invoke() a second time", async () => {
    mockListen.mockResolvedValue(() => {});
    // First invoke: slow so the key stays in inFlight during the second call.
    let resolveFirst!: (v: unknown) => void;
    const firstPromise = new Promise((res) => {
      resolveFirst = res;
    });
    mockInvoke.mockReturnValueOnce(firstPromise as ReturnType<typeof invoke>);

    const { result } = renderHook(() => useInvokeStore());

    // First dispatch — starts but does not finish.
    act(() => {
      void result.current.dispatch(
        "prd",
        "my-slug",
        "/repo/path",
        "card-action",
        "terminal",
      );
    });

    // Key is now in inFlight; second dispatch must be blocked.
    await act(async () => {
      await result.current.dispatch(
        "prd",
        "my-slug",
        "/repo/path",
        "card-action",
        "terminal",
      );
    });

    // invoke() must have been called exactly once.
    expect(mockInvoke).toHaveBeenCalledTimes(1);

    // Settle the first promise to clean up.
    await act(async () => {
      resolveFirst({ outcome: "spawned" });
      await firstPromise;
    });
  });

  // -------------------------------------------------------------------------
  // Test 6: outcome === 'failed' triggers second invoke() with delivery: 'clipboard'.
  // -------------------------------------------------------------------------
  it("outcome 'failed' triggers a second invoke() call with delivery: 'clipboard'", async () => {
    mockListen.mockResolvedValue(() => {});
    // First call returns failed; second call returns copied (clipboard fallback).
    mockInvoke
      .mockResolvedValueOnce({ outcome: "failed" })
      .mockResolvedValueOnce({ outcome: "copied" });

    const { result } = renderHook(() => useInvokeStore());

    await act(async () => {
      await result.current.dispatch(
        "prd",
        "my-slug",
        "/repo/path",
        "card-action",
        "terminal",
      );
    });

    // invoke() must have been called twice.
    expect(mockInvoke).toHaveBeenCalledTimes(2);

    // The second call must have delivery: 'clipboard'.
    const secondCallArgs = mockInvoke.mock.calls[1][1] as Record<string, unknown>;
    expect(secondCallArgs.delivery).toBe("clipboard");
  });

  // -------------------------------------------------------------------------
  // Test 7: outcome === 'spawned' with a WRITE command sets PreflightToast state.
  // -------------------------------------------------------------------------
  it("outcome 'spawned' with a WRITE-classified command sets preflightCommand and preflightSlug", async () => {
    mockListen.mockResolvedValue(() => {});
    mockInvoke.mockResolvedValue({ outcome: "spawned" });

    const { result } = renderHook(() => useInvokeStore());

    await act(async () => {
      await result.current.dispatch(
        "prd",       // 'prd' is WRITE-classified
        "my-slug",
        "/repo/path",
        "card-action",
        "terminal",  // PreflightToast only fires on terminal delivery
      );
    });

    // PreflightToast state must be populated with the command and slug.
    expect(result.current.preflightCommand).toBe("prd");
    expect(result.current.preflightSlug).toBe("my-slug");
  });
});
