/// Command taxonomy: closed enum of classifications + lookup helpers.
///
/// D3: the 16 specflow commands are grouped into three risk classes so that
/// the invoke path can apply the correct gate (no-confirm for Safe, one-confirm
/// for Write, two-confirm for Destroy) without duplicating the list in frontend
/// and backend code. The TS projection is generated by build.rs (T109).
///
/// The list is intentionally hardcoded — adding a new specflow command must
/// be a deliberate multi-file change (here + build.rs output + ipc.rs handler)
/// so that reviewers cannot miss an unclassified command.

/// Risk classification for a specflow command.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Classification {
    Safe,
    Write,
    Destroy,
}

/// Commands that are read-only or advisory — no artefact mutation.
/// 4 entries.
pub const SAFE: &[&str] = &["next", "review", "remember", "promote"];

/// Commands that create or update artefacts — reversible with git.
/// 7 entries.
pub const WRITE: &[&str] = &["request", "prd", "tech", "plan", "implement", "validate", "design"];

/// Commands that delete, overwrite, or restructure committed artefacts.
/// 5 entries.
pub const DESTROY: &[&str] = &["archive", "update-req", "update-tech", "update-plan", "update-task"];

/// Classify a command name.  Returns `None` for unrecognised commands.
pub fn classify(cmd: &str) -> Option<Classification> {
    if SAFE.contains(&cmd) {
        return Some(Classification::Safe);
    }
    if WRITE.contains(&cmd) {
        return Some(Classification::Write);
    }
    if DESTROY.contains(&cmd) {
        return Some(Classification::Destroy);
    }
    None
}

/// Returns `true` if `cmd` appears in the combined SAFE ∪ WRITE ∪ DESTROY
/// allow-list; `false` for any unrecognised command string.
pub fn allow_list_contains(cmd: &str) -> bool {
    classify(cmd).is_some()
}

// ---------------------------------------------------------------------------
// Tests — Seam B partial
// ---------------------------------------------------------------------------
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn total_count_is_16() {
        assert_eq!(SAFE.len() + WRITE.len() + DESTROY.len(), 16);
    }

    #[test]
    fn safe_count_is_4() {
        assert_eq!(SAFE.len(), 4);
    }

    #[test]
    fn write_count_is_7() {
        assert_eq!(WRITE.len(), 7);
    }

    #[test]
    fn destroy_count_is_5() {
        assert_eq!(DESTROY.len(), 5);
    }

    #[test]
    fn unknown_command_returns_none() {
        assert_eq!(classify("nonexistent"), None);
        assert_eq!(classify(""), None);
        assert_eq!(classify("ARCHIVE"), None); // case-sensitive
    }

    #[test]
    fn safe_commands_classified_correctly() {
        for cmd in SAFE {
            assert_eq!(
                classify(cmd),
                Some(Classification::Safe),
                "expected Safe for {:?}",
                cmd
            );
        }
    }

    #[test]
    fn write_commands_classified_correctly() {
        for cmd in WRITE {
            assert_eq!(
                classify(cmd),
                Some(Classification::Write),
                "expected Write for {:?}",
                cmd
            );
        }
    }

    #[test]
    fn destroy_commands_classified_correctly() {
        for cmd in DESTROY {
            assert_eq!(
                classify(cmd),
                Some(Classification::Destroy),
                "expected Destroy for {:?}",
                cmd
            );
        }
    }

    #[test]
    fn allow_list_contains_all_16() {
        for cmd in SAFE.iter().chain(WRITE).chain(DESTROY) {
            assert!(
                allow_list_contains(cmd),
                "expected allow_list_contains to return true for {:?}",
                cmd
            );
        }
    }

    #[test]
    fn allow_list_rejects_unknown() {
        assert!(!allow_list_contains("nonexistent"));
        assert!(!allow_list_contains(""));
    }

    #[test]
    fn each_of_16_returns_expected_classification() {
        // SAFE
        assert_eq!(classify("next"), Some(Classification::Safe));
        assert_eq!(classify("review"), Some(Classification::Safe));
        assert_eq!(classify("remember"), Some(Classification::Safe));
        assert_eq!(classify("promote"), Some(Classification::Safe));
        // WRITE
        assert_eq!(classify("request"), Some(Classification::Write));
        assert_eq!(classify("prd"), Some(Classification::Write));
        assert_eq!(classify("tech"), Some(Classification::Write));
        assert_eq!(classify("plan"), Some(Classification::Write));
        assert_eq!(classify("implement"), Some(Classification::Write));
        assert_eq!(classify("validate"), Some(Classification::Write));
        assert_eq!(classify("design"), Some(Classification::Write));
        // DESTROY
        assert_eq!(classify("archive"), Some(Classification::Destroy));
        assert_eq!(classify("update-req"), Some(Classification::Destroy));
        assert_eq!(classify("update-tech"), Some(Classification::Destroy));
        assert_eq!(classify("update-plan"), Some(Classification::Destroy));
        assert_eq!(classify("update-task"), Some(Classification::Destroy));
    }

    #[test]
    fn retired_stubs_not_in_taxonomy() {
        // brainstorm, tasks, verify, gap-check are RETIRED — must not classify
        assert_eq!(classify("brainstorm"), None);
        assert_eq!(classify("tasks"), None);
        assert_eq!(classify("verify"), None);
        assert_eq!(classify("gap-check"), None);
    }
}
